server:
  tomcat:
    max-threads: 32
    max-connections: 128
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/file_server?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      mininum-idle: 5
      maxinum-pool-size: 25
      idle-timeout: 30000
      pool-name: fs-server-pool
      max-lifetime: 180000
      connection-timeout: 10000
      connection-test-query: /* ping */

file-server:
  max-threads: 128
  max-upload-concurrent: 192
  temp-root: /Users/hexiufeng/fs-root/temp
  default-store-root: /Users/hexiufeng/fs-root/data
  config-bean-name: simpleFsConfig
  login-validate-bean-name: debugLoginValidator