#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.github.rolandhe.fileserver.ctrl.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true